### ISSUE TITLE
Dart extension for VS Code not working on v `3.23.1`

### ISSUE THREAD

**Issue by CaptainDario** [Dart-Code/Dart-Code#3427]
**Describe the bug**
The newest version of the vs code dart plugin does not start.
I get the following error:
```
Activating extension 'Dart-Code.dart-code' failed: Cannot find module 'c:\Users\dario\.vscode\extensions\dart-code.dart-code-3.23.1\out\dist\extension'
Require stack:
- c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork.js.
```
However everything works flawless with `3.23.0`.

**To Reproduce**
Install `dart==3.23.1` from the extensions manager

**Expected behavior**
Everything should work fine like in `3.23.0`.

**Versions:**
 - VS Code version: Version: 1.57.1 (system setup)
 - Dart extension version: 3.23.1
 - Dart/Flutter SDK version: Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1081], locale en-US)

**Comment by DanTup** [comment]
This looks to me like the extension code is somehow corrupt/missing from your machine. Please try:

- Uninstall whichever version you have installed (you'll also need to uninstall Flutter in order to uninstall Dart) 
- Delete the folder `c:\Users\dario\.vscode\extensions\dart-code.dart-code-3.23.1`
- Re-installing v3.23.1 of the Dart extension
- Re-install the Flutter extension

Please let me know if you still have issues!

**Comment by CaptainDario** [comment]
Sorry, it was my fault for assuming uninstalling the extension would remove it entirely.
After removing `c:\Users\dario\.vscode\extensions\dart-code.dart-code-3.23.1` everything works as expected.

Thank you!

**Comment by DanTup** [comment]
> Sorry, it was my fault for assuming uninstalling the extension would remove it entirely.

I assumed that too, but discovered it didn't when someone previously reported an issue like this. I don't know how you ended up with this file missing, but a few people have reported VS Code not extracting extensions correctly and seeing issues like these (unfortunately that extracting is outside of our code, since it's extracting our code!).

Glad it's working now in any case!
