### ISSUE TITLE
"Starting debug session..." can appear for longer than just startup

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#6133]
When running `test_all.dart` script in the SDK, there is no output until the test run completes/failures (since https://github.com/dart-lang/test/pull/2685). We show "Starting debug session..." until we get some output, which makes it seem like we're taking a long time to start.

We should check if there are any other events we could use to hide this, that don't mitigate the reason it was added.

```
[3:03:44 PM] [General] [Info] Using dart debugger for Dart
[3:03:44 PM] [General] [Info] SDK DAP setting is true for debugger 0
[3:03:44 PM] [General] [Info] Running SDK DAP Dart VM in undefined: D:\Tools\Dart\Latest (Bleeding Edge)\bin\dart.exe debug_adapter and options {"env":{"FLUTTER_HOST":"VSCode","DASH__IDE_NAME":"Visual Studio Code","DASH__IDE_VERSION":"1.131.0","DASH__PLUGIN_NAME":"Dart-Code","DASH__PLUGIN_VERSION":"3.139.20260716","DASH__IDE_ENVIRONMENT":"desktop","DASH__TOOL":"vscode-plugins","DASH__SUPPRESS_ANALYTICS":"true"}}
[3:03:44 PM] [DAP] [Info] Starting debug session 290a9719-dda1-40f8-8866-fd964ef7ccdb
[3:03:44 PM] [DAP] [Info] ==> {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"dart","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true,"supportsArgsCanBeInterpretedByShell":true,"supportsMemoryEvent":true,"supportsStartDebuggingRequest":true,"supportsANSIStyling":true},"type":"request","seq":1}
[3:03:44 PM] [DAP] [Info] <== {"seq":1,"type":"response","body":{"exceptionBreakpointFilters":[{"default":false,"filter":"All","label":"All Exceptions"},{"default":true,"filter":"Unhandled","label":"Uncaught Exceptions"}],"supportsANSIStyling":true,"supportsClipboardContext":true,"supportsConditionalBreakpoints":true,"supportsConfigurationDoneRequest":true,"supportsDelayedStackTraceLoading":true,"supportsEvaluateForHovers":true,"supportsLogPoints":true,"supportsRestartFrame":true,"supportsRestartRequest":false,"supportsTerminateRequest":true,"supportsValueFormattingOptions":true},"command":"initialize","request_seq":1,"success":true}
[3:03:44 PM] [DAP] [Info] <== {"seq":2,"type":"event","body":{},"event":"initialized"}
[3:03:44 PM] [DAP] [Info] ==> {"command":"launch","arguments":{"name":"Current file","request":"launch","type":"dart","program":"D:\\Dev\\Google\\dart-sdk\\sdk\\pkg\\analysis_server\\test\\lsp\\code_lens\\test_all.dart","__configurationTarget":6,"noDebug":true,"dartCodeDebugSessionID":"session-76674","projectRootPath":"D:\\Dev\\Google\\dart-sdk\\sdk\\pkg\\analysis_server","cwd":"D:\\Dev\\Google\\dart-sdk\\sdk\\pkg\\analysis_server","toolEnv":{"FLUTTER_HOST":"VSCode","DASH__IDE_NAME":"Visual Studio Code","DASH__IDE_VERSION":"1.131.0","DASH__PLUGIN_NAME":"Dart-Code","DASH__PLUGIN_VERSION":"3.139.20260716","DASH__IDE_ENVIRONMENT":"desktop","DASH__TOOL":"vscode-plugins","DASH__SUPPRESS_ANALYTICS":"true"},"sendLogsToClient":true,"sendCustomProgressEvents":true,"allowAnsiColorOutput":true,"additionalProjectPaths":["D:\\Dev\\Google\\dart-sdk\\sdk\\pkg\\analysis_server","D:\\Dev\\Google\\dart-sdk\\sdk\\pkg\\analyzer","D:\\Dev\\Google\\dart-sdk\\sdk\\pkg\\analyzer_plugin","D:\\Dev\\Google\\dart-sdk\\sdk\\pkg\\analysis_server_client","D:\\Dev\\Google\\dart-sdk\\sdk\\pkg\\analyzer_utilities","D:\\Dev\\Google\\dart-sdk\\sdk\\pkg\\dartdev","D:\\Dev\\Google\\dart-sdk\\sdk\\third_party\\pkg\\language_server_protocol","D:\\Dev\\Google\\dart-sdk\\sdk\\pkg\\linter","D:\\Dev\\Google\\dart-sdk\\sdk\\pkg\\analyzer_cli","D:\\Dev\\Google\\dart-sdk\\sdk\\pkg\\_fe_analyzer_shared","D:\\Dev\\Google\\dart-sdk\\sdk\\pkg\\scrape","D:\\Dev\\Google\\dart-sdk\\sdk\\pkg\\analysis_server_plugin","D:\\Dev\\Google\\dart-sdk\\sdk\\pkg\\test_runner","D:\\Dev\\Google\\dart-sdk\\sdk\\pkg\\analyzer_testing"],"args":[],"vmAdditionalArgs":[],"toolArgs":["--enable-asserts"],"vmServicePort":0,"dartSdkPath":"D:\\Tools\\Dart\\Latest (Bleeding Edge)","webDaemonLogFile":"D:\\Logs\\dart_analysis_server_workspace_web_daemon.current_file.txt","maxLogLineLength":99999999,"debugSdkLibraries":false,"debugExternalPackageLibraries":false,"showDartDeveloperLogs":true,"evaluateGettersInDebugViews":true,"showGettersInDebugViews":true,"evaluateToStringInDebugViews":true,"console":"debugConsole","debuggerType":0,"__sessionId":"290a9719-dda1-40f8-8866-fd964ef7ccdb"},"type":"request","seq":2}
[3:03:44 PM] [DAP] [Info] ==> {"command":"configurationDone","type":"request","seq":3}
[3:03:44 PM] [DAP] [Info] <== {"seq":3,"type":"response","command":"configurationDone","request_seq":3,"success":true}
[3:03:44 PM] [DAP] [Info] ==> {"command":"threads","type":"request","seq":4}
[3:03:44 PM] [DAP] [Info] <== {"seq":4,"type":"response","command":"launch","request_seq":2,"success":true}
[3:03:44 PM] [DAP] [Info] <== {"seq":5,"type":"response","body":{"threads":[]},"command":"threads","request_seq":4,"success":true}
[3:03:44 PM] [DartToolingDaemon] [Info] ==> {"jsonrpc":"2.0","method":"postEvent","params":{"eventData":{"debugSession":{"debuggerType":"Dart","id":"290a9719-dda1-40f8-8866-fd964ef7ccdb","name":"Current file","projectRootPath":"D:\\Dev\\Google\\dart-sdk\\sdk\\pkg\\analysis_server"}},"eventKind":"debugSessionStarted","streamId":"Editor"}}
[3:03:53 PM] [DAP] [Info] <== {"seq":6,"type":"event","body":{"category":"stdout","output":"+28: All tests passed!\n"},"event":"output"}
[3:03:53 PM] [DAP] [Info] <== {"seq":7,"type":"event","body":{"category":"stdout","output":"\n"},"event":"output"}
Wed Jul 29 2026 [15:03:54 GMT+0100 (British Summer Time)] Log file ended
```

**Comment by DanTup** [comment]
Similar here in 'flutter analyze' tests

<img width="732" height="490" alt="Image" src="https://github.com/user-attachments/assets/898267f9-3e28-4638-a7a2-6f6401f7600a" />

```
[12:20:35 PM] [DAP] [Info] Starting debug session 21b368b3-6bad-4ac3-8c14-dbbf3a5882dd
[12:20:35 PM] [DAP] [Info] ==> {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"dart","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true,"supportsArgsCanBeInterpretedByShell":true,"supportsMemoryEvent":true,"supportsStartDebuggingRequest":true,"supportsANSIStyling":true},"type":"request","seq":1}
[12:20:35 PM] [DAP] [Info] <== {"seq":1,"type":"response","body":{"exceptionBreakpointFilters":[{"default":false,"filter":"All","label":"All Exceptions"},{"default":true,"filter":"Unhandled","label":"Uncaught Exceptions"}],"supportsANSIStyling":true,"supportsClipboardContext":true,"supportsConditionalBreakpoints":true,"supportsConfigurationDoneRequest":true,"supportsDelayedStackTraceLoading":true,"supportsEvaluateForHovers":true,"supportsLogPoints":true,"supportsRestartFrame":true,"supportsRestartRequest":false,"supportsTerminateRequest":true,"supportsValueFormattingOptions":true},"command":"initialize","request_seq":1,"success":true}
[12:20:35 PM] [DAP] [Info] <== {"seq":2,"type":"event","body":{},"event":"initialized"}
[12:20:35 PM] [DAP] [Info] ==> {"command":"launch","arguments":{"suppressPrompts":false,"name":"Run","noDebug":true,"request":"launch","type":"dart","templateFor":"","env":{},"expectSingleTest":true,"program":"D:\\Dev\\Google\\Flutter\\Flutter main\\packages\\flutter_tools\\test\\commands.shard\\hermetic\\analyze_continuously_test.dart","toolArgs":["--name","^DANNY( \\(variant: .*\\))?$","--run-skipped"],"dartCodeDebugSessionID":"session-f04b8","projectRootPath":"D:\\Dev\\Google\\Flutter\\Flutter main\\packages\\flutter_tools","cwd":"D:\\Dev\\Google\\Flutter\\Flutter main\\packages\\flutter_tools","toolEnv":{"FLUTTER_HOST":"VSCode","FLUTTER_ROOT":"D:\\Dev\\Google\\Flutter\\Flutter main","DASH__IDE_NAME":"Visual Studio Code","DASH__IDE_VERSION":"1.132.0","DASH__PLUGIN_NAME":"Dart-Code","DASH__PLUGIN_VERSION":"3.141.20260803","DASH__IDE_ENVIRONMENT":"desktop","DASH__TOOL":"vscode-plugins","DASH__SUPPRESS_ANALYTICS":"true"},"sendLogsToClient":true,"sendCustomProgressEvents":true,"allowAnsiColorOutput":true,"additionalProjectPaths":["D:\\Dev\\Google\\Flutter\\Flutter main\\packages\\flutter_tools","D:\\Dev\\Google\\Flutter\\Flutter main\\packages\\flutter_test","D:\\Dev\\Google\\Flutter\\Flutter main\\dev\\bots"],"args":[],"vmAdditionalArgs":[],"vmServicePort":0,"dartSdkPath":"D:\\Dev\\Google\\Flutter\\Flutter main\\bin\\cache\\dart-sdk","webDaemonLogFile":"D:\\Logs\\flutter_tools_workspace_web_daemon.run.txt","maxLogLineLength":99999999,"debugSdkLibraries":false,"debugExternalPackageLibraries":false,"showDartDeveloperLogs":true,"evaluateGettersInDebugViews":true,"showGettersInDebugViews":true,"evaluateToStringInDebugViews":true,"debuggerType":1,"__sessionId":"21b368b3-6bad-4ac3-8c14-dbbf3a5882dd"},"type":"request","seq":2}
[12:20:35 PM] [DAP] [Info] ==> {"command":"configurationDone","type":"request","seq":3}
[12:20:35 PM] [DAP] [Info] <== {"seq":3,"type":"response","command":"configurationDone","request_seq":3,"success":true}
[12:20:35 PM] [DAP] [Info] ==> {"command":"threads","type":"request","seq":4}
[12:20:35 PM] [DAP] [Info] <== {"seq":4,"type":"response","command":"launch","request_seq":2,"success":true}
[12:20:35 PM] [DAP] [Info] <== {"seq":5,"type":"response","body":{"threads":[]},"command":"threads","request_seq":4,"success":true}
[12:20:35 PM] [DartToolingDaemon] [Info] ==> {"jsonrpc":"2.0","method":"postEvent","params":{"eventData":{"debugSession":{"debuggerType":"DartTest","id":"21b368b3-6bad-4ac3-8c14-dbbf3a5882dd","name":"Run","projectRootPath":"D:\\Dev\\Google\\Flutter\\Flutter main\\packages\\flutter_tools"}},"eventKind":"debugSessionStarted","streamId":"Editor"}}
[12:20:35 PM] [DAP] [Info] <== {"seq":6,"type":"event","body":{"protocolVersion":"0.1.1","runnerVersion":"1.31.1","pid":8472,"type":"start","time":0},"event":"dart.testNotification"}
[12:20:35 PM] [DAP] [Info] <== {"seq":7,"type":"event","body":{"suite":{"id":0,"platform":"vm","path":"D:/Dev/Google/Flutter/Flutter main/packages/flutter_tools/test/commands.shard/hermetic/analyze_continuously_test.dart"},"type":"suite","time":0},"event":"dart.testNotification"}
[12:20:35 PM] [DAP] [Info] <== {"seq":8,"type":"event","body":{"test":{"id":1,"name":"loading D:/Dev/Google/Flutter/Flutter main/packages/flutter_tools/test/commands.shard/hermetic/analyze_continuously_test.dart","suiteID":0,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":0},"event":"dart.testNotification"}
[12:20:35 PM] [DAP] [Info] <== {"seq":9,"type":"event","body":{"count":1,"time":5,"type":"allSuites"},"event":"dart.testNotification"}
[12:20:36 PM] [DAP] [Info] <== {"seq":10,"type":"event","body":{"testID":1,"result":"success","skipped":false,"hidden":true,"type":"testDone","time":679},"event":"dart.testNotification"}
```
